version: "2.2"
services:
    odoo:
        image: $ODOO_IMAGE:$ODOO_MINOR
        networks:
            - default
        volumes:
            - ./odoo/custom/src:/opt/odoo/custom/src:rw,z
        environment:
            DEPTH_DEFAULT: 100
            UID: "${UID:-1000}"
            GID: "${GID:-1000}"
            UMASK: "${UMASK:-0022}"
            PROJECT_NAME: "$PROJECT_NAME"
            PROJECT_BRANCH: "$PROJECT_BRANCH"
        user: root
        entrypoint: autoaggregate

networks:
    default:
